<a href="https://colab.research.google.com/github/Akshitha94127/NASSCOM/blob/main/Copy_of_NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")
print("\n--- Task 1: Array Creation Shortcuts ---")

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---


In [ ]:
#task 1.1
arr1_1=[1,2,3,4]
print("arr1_1 (first 10 elements):", arr1_1[:10])

arr1_1 (first 10 elements): [1, 2, 3, 4]


In [ ]:
#task 1.2
arr1_2=[10,20,30,40]
print("arr1_2:\n", arr1_2)

arr1_2:
 [10, 20, 30, 40]


In [ ]:
#task 1.3
arr1_3=[100,200,300,400]
print("arr1_3:\n", arr1_3)

arr1_3:
 [100, 200, 300, 400]


In [ ]:
#task 1.4
arr1_4=[25,50,75,100]
print("arr1_4 (first 2 rows):\n", arr1_4[:2])

arr1_4 (first 2 rows):
 [25, 50]


In [ ]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
#task 2.1
val2_1 = data[2, 3]
print("2.1 =", val2_1)
#task 2.2
row2_2 = data[0]
print("2.2 =", row2_2)
#task 2.3
col2_3 = data[:, 3]
print("2.3 =")
print(col2_3)
#task 2.4
sub_arr2_4 = data[1:3, 0:2]
print("2.4 =")
print(sub_arr2_4)
#task 2.5
filtered_elements2_5 = data[data > 100]
print("2.5 =", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
2.1 = 120
2.2 = [10 20 30 40]
2.3 =
[ 40  80 120 160]
2.4 =
[[ 50  60]
 [ 90 100]]
2.5 = [110 120 130 140 150 160]


In [ ]:
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
#task 3.1
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print("arr3_2:\n", arr3_2)
#task 3.2
even_count3_3 = np.sum(arr3_1 % 2 == 0)
print("even_count3_3:", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_2:
 [[17 15 11 10 14]
 [ 0 20  0  0  0]
 [ 0  0 13  0 18]
 [17  0  0  0 13]]
even_count3_3: 8


In [ ]:
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
#task 4.1
sum4_1 = np.sum(arr4_1)
print("sum4_1:", sum4_1)
#task 4.2
mean_cols4_2 = np.mean(arr4_1, axis=0)
print("mean_cols4_2:", mean_cols4_2)
#task 4.3
max_rows4_3 = np.max(arr4_1, axis=1)
print("max_rows4_3:", max_rows4_3)
#task 4.4
std4_4 = np.std(arr4_1)
print("std4_4:", std4_4)


--- Task 4: Aggregation Functions ---
sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405


In [ ]:
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23
#task 5.1
reshaped_arr5_2 = arr5_1.reshape(4, 6)
print("reshaped_arr5_2:\n", reshaped_arr5_2)
#task 5.2
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
print("reshaped_arr5_3:\n", reshaped_arr5_3)
#task 5.3
flattened_arr5_4 = reshaped_arr5_2.flatten()
print("flattened_arr5_4:", flattened_arr5_4)
#task 5.4
print("ravel():", reshaped_arr5_2.ravel())
print("flatten():", reshaped_arr5_2.flatten())


--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened_arr5_4: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])
#task 6.1
result6_1 = arr6_1 + scalar
print("result6_1:\n", result6_1)
#task 6.2
result6_2 = arr6_1 + vector
print("result6_2:\n", result6_2)


--- Task 6: Broadcasting ---
result6_1:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
result6_2:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [ ]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])
#task 7.1
view_arr7 = original_arr7[:]
view_arr7[0] = 99
print("view_arr7:", view_arr7)
print("original_arr7:", original_arr7)
#task 7.2
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0
print("copy_arr7:", copy_arr7)
print("original_arr7:", original_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
view_arr7: [99  2  3  4  5]
original_arr7: [99  2  3  4  5]
copy_arr7: [99  2  3  4  0]
original_arr7: [99  2  3  4  5]


In [ ]:
import numpy as np
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])
#task 8.1
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
#task 8.2
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
#task 8.3
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))
print(vstack_arr8_1)
print(hstack_arr8_2)
print(combined_arr8_3)
#task 8.4
arr8_c = np.array([[9, 10],
                   [11, 12]])
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3 = np.vsplit(combined_arr8_3, 3)

print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


--- Task 8: Stacking and Splitting Arrays ---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Part 1:
 [[1 2]
 [3 4]]
Part 2:
 [[5 6]
 [7 8]]
Part 3:
 [[ 9 10]
 [11 12]]


In [ ]:
import numpy as np
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
# 9.1 Sort 'arr9_1' in ascending order
sorted_arr9_1 = np.sort(arr9_1)
# 9.2 Sort 'arr9_2d' along columns
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
# 9.3 Find the indices where the value 9 is present
idx9_3 = np.where(arr9_1 == 9)
# 9.4 Find the index of the maximum value
max_idx9_4 = np.argmax(arr9_1)
# Print the results
print("Sorted arr9_1:", sorted_arr9_1)
print("Sorted columns:\n", sorted_cols9_2)
print("Index of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)


--- Task 9: Sorting and Searching ---
Sorted arr9_1: [1 2 3 4 5 6 7 8 9]
Sorted columns:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Index of value 9: (array([4]),)
Index of maximum value: 4
