<a href="https://colab.research.google.com/github/Akshitha94127/NASSCOM/blob/main/Copy_of_Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------


In [ ]:
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
import numpy as np
import pandas as pd
#task 1.1
s1_1 = pd.Series([10, 20, 30, 40, 50])
print("--- s1_1 Output ---")
print(s1_1)
print()
#task 1.2
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print("--- np_array1_2 Output ---")
print(np_array1_2)
print()
#task 1.3
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("--- df1_3 Output ---")
print(df1_3)


--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
--- s1_1 Output ---
0    10
1    20
2    30
3    40
4    50
dtype: int64

--- np_array1_2 Output ---
[[ 4 60  8 39]
 [ 4 93 58 17]
 [71  3 12 17]]

--- df1_3 Output ---
    A   B   C   D
0   4  60   8  39
1   4  93  58  17
2  71   3  12  17


In [ ]:
import numpy as np
import pandas as pd
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
np.random.seed(42)
available_dates = pd.date_range(start="2023-01-01", end="2023-04-09", freq="D")
sampled_dates = np.random.choice(available_dates, size=100)
df_sales = pd.DataFrame(
    {
        "Date": sampled_dates,
        "Region": np.random.choice(["East", "West", "North", "South"], size=100),
        "Product": np.random.choice(
            ["Laptop", "Mouse", "Keyboard", "Monitor"], size=100
        ),
        "Sales": np.random.randint(100, 1001, size=100).astype(
            float
        ),
        "Quantity": np.random.randint(1, 11, size=100).astype(float),
    }
)
sales_nan_indices = np.random.choice(100, size=5, replace=False)
quantity_nan_indices = np.random.choice(100, size=3, replace=False)
df_sales.loc[sales_nan_indices, "Sales"] = np.nan
df_sales.loc[quantity_nan_indices, "Quantity"] = np.nan
print("\n--- First 10 Rows of df_sales ---")
print(df_sales.head(10))
print("\n--- Missing Value Count Verification ---")
print(df_sales.isna().sum())



--- Task 2: Synthetic Data Generation for Practice ---

--- First 10 Rows of df_sales ---
        Date Region  Product  Sales  Quantity
0 2023-02-21  South   Laptop  851.0       7.0
1 2023-04-03  South   Laptop  243.0       6.0
2 2023-01-15  South    Mouse  708.0       6.0
3 2023-03-13   East  Monitor  300.0       6.0
4 2023-03-02   East  Monitor  223.0       3.0
5 2023-01-21   East  Monitor    NaN       6.0
6 2023-03-24  North  Monitor  425.0       8.0
7 2023-03-28   East  Monitor  563.0       2.0
8 2023-03-16   East    Mouse  448.0       5.0
9 2023-03-16   East    Mouse  870.0       1.0

--- Missing Value Count Verification ---
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64


In [ ]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
#task 3.1
df3_1 = df_sales[['Region', 'Sales']]
print("\n--- 3.1: df3_1 (First 5 Rows) ---")
print(df3_1.head())
#task 3.2
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print("\n--- 3.2: df3_2 (First 5 Rows) ---")
print(df3_2.head())
#task 3.3
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print("\n--- 3.3: df3_3 (First 5 Rows) ---")
print(df3_3.head())
#task 3.4
monitor_df = df_sales[df_sales['Product'] == 'Monitor']
val3_4_iloc = monitor_df.iloc[0, monitor_df.columns.get_loc('Sales')]
first_monitor_label = monitor_df.index[0]
val3_4 = monitor_df.loc[first_monitor_label, 'Sales']
print("\n--- 3.4: val3_4 Value ---")
print(f"Sales value (via .iloc): {val3_4_iloc}")
print(f"Sales value (via .loc):  {val3_4}")


--- Task 3: Indexing and Slicing in DataFrames ---

--- 3.1: df3_1 (First 5 Rows) ---
  Region  Sales
0  South  851.0
1  South  243.0
2  South  708.0
3   East  300.0
4   East  223.0

--- 3.2: df3_2 (First 5 Rows) ---
         Date Region Product  Sales  Quantity
0  2023-02-21  South  Laptop  851.0       7.0
1  2023-04-03  South  Laptop  243.0       6.0
15 2023-01-02  South  Laptop  246.0       1.0
18 2023-02-07  North  Laptop  810.0       6.0
19 2023-01-02  North  Laptop  919.0       3.0

--- 3.3: df3_3 (First 5 Rows) ---
         Date Region  Product  Sales  Quantity
7  2023-03-28   East  Monitor  563.0       2.0
9  2023-03-16   East    Mouse  870.0       1.0
11 2023-01-24   East  Monitor  863.0       5.0
20 2023-03-05   East   Laptop  588.0       9.0
24 2023-03-17   East  Monitor  971.0       5.0

--- 3.4: val3_4 Value ---
Sales value (via .iloc): 300.0
Sales value (via .loc):  300.0


In [ ]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
#task 4.1
missing_counts4_1 = df_sales.isna().sum()
print("\n--- 4.1: missing_counts4_1 ---")
print(missing_counts4_1)
#task 4.2
df4_2_filled = df_sales.copy()
sales_mean = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)
print("\n--- 4.2: df4_2_filled 'Sales' Missing Count ---")
print(f"Remaining missing values in Sales: {df4_2_filled['Sales'].isna().sum()}")
print(f"Filled with Mean Value: {sales_mean:.2f}")
#task 4.3
df4_3_dropped = df_sales.dropna()
print("\n--- 4.3: df4_3_dropped Summary ---")
print(f"Original Row Count: {len(df_sales)}")
print(f"Cleaned Row Count:  {len(df4_3_dropped)}")
print(f"Total Rows Dropped: {len(df_sales) - len(df4_3_dropped)}")



--- Task 4: Data Cleaning (Handling Missing Values) ---

--- 4.1: missing_counts4_1 ---
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

--- 4.2: df4_2_filled 'Sales' Missing Count ---
Remaining missing values in Sales: 0
Filled with Mean Value: 544.43

--- 4.3: df4_3_dropped Summary ---
Original Row Count: 100
Cleaned Row Count:  92
Total Rows Dropped: 8


In [ ]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
#task 5.1
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
print("\n--- 5.1: df_sales with Total_Revenue (First 5 Rows) ---")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']].head())
#task 5.2
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
print("\n--- 5.2: df5_2_sorted (First 5 Rows) ---")
print(df5_2_sorted.head())
#task 5.3
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
print("\n--- 5.3: df5_3_grouped_region ---")
print(df5_3_grouped_region)
#task 5.4
df5_4_grouped_product = df_sales.groupby('Product')[['Sales']].mean()
print("\n--- 5.4: df5_4_grouped_product ---")
print(df5_4_grouped_product)



--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

--- 5.1: df_sales with Total_Revenue (First 5 Rows) ---
   Sales  Quantity  Total_Revenue
0  851.0       7.0         5957.0
1  243.0       6.0         1458.0
2  708.0       6.0         4248.0
3  300.0       6.0         1800.0
4  223.0       3.0          669.0

--- 5.2: df5_2_sorted (First 5 Rows) ---
         Date Region   Product  Sales  Quantity  Total_Revenue
19 2023-01-02  North    Laptop  919.0       3.0         2757.0
15 2023-01-02  South    Laptop  246.0       1.0          246.0
57 2023-01-02   East  Keyboard  219.0       2.0          438.0
71 2023-01-02  North   Monitor  198.0       7.0         1386.0
12 2023-01-03  South     Mouse  502.0       3.0         1506.0

--- 5.3: df5_3_grouped_region ---
          Sales  Quantity
Region                   
East    15731.0     134.0
North   15974.0     195.0
South   11687.0     116.0
West     8329.0      86.0

--- 5.4: df5_4_grouped_product ---
               Sales
Product